# Generated by Django 4.2.5 on 2023-09-27 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Titulado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Run', models.CharField(max_length=11, unique=True)),
                ('Nombres', models.CharField(max_length=50)),
                ('ApellidoP', models.CharField(max_length=50)),
                ('ApellidoM', models.CharField(max_length=50)),
                ('NCeluda', models.CharField(max_length=10)),
                ('Celular', models.CharField(max_length=10)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Contrasena', models.CharField(max_length=50)),
                ('Carrera', models.CharField(max_length=50)),
                ('Codigo', models.IntegerField(unique=True)),
                ('Invitado1', models.CharField(blank=True, max_length=50, null=True)),
                ('Invitado2', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
