# Generated by Django 4.2.1 on 2023-10-03 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='titulado',
            name='Contrasena',
        ),
        migrations.AddField(
            model_name='titulado',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
