# Generated by Django 4.2.1 on 2023-10-04 01:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Web', '0002_remove_titulado_contrasena_titulado_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titulado',
            name='Run',
            field=models.CharField(default=0, max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='titulado',
            name='usuario',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
