# Generated by Django 4.2.1 on 2023-10-24 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0003_alter_titulado_nasiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='titulado',
            name='PaginaLibro',
            field=models.CharField(default='0', max_length=3),
        ),
    ]
