# Generated by Django 4.2.1 on 2023-10-04 01:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0004_alter_titulado_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titulado',
            name='Codigo',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
