# Generated by Django 4.2.1 on 2023-10-09 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0011_alter_titulado_run'),
    ]

    operations = [
        migrations.RenameField(
            model_name='titulado',
            old_name='CodigoAsiento',
            new_name='NAsiento',
        ),
        migrations.RemoveField(
            model_name='titulado',
            name='ApellidoM',
        ),
        migrations.RemoveField(
            model_name='titulado',
            name='ApellidoP',
        ),
        migrations.RemoveField(
            model_name='titulado',
            name='Nombres',
        ),
        migrations.AddField(
            model_name='titulado',
            name='custom_password',
            field=models.CharField(default='titulados', max_length=128),
        ),
        migrations.AlterField(
            model_name='titulado',
            name='usuario',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
