# Generated by Django 4.2.1 on 2023-10-09 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0012_rename_codigoasiento_titulado_nasiento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='titulado',
            old_name='custom_password',
            new_name='password',
        ),
    ]
