# Generated by Django 4.2.1 on 2023-10-10 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0013_rename_custom_password_titulado_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='titulado',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='titulado',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='titulado',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='titulado',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
