# Generated by Django 4.2.1 on 2023-10-10 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0014_titulado_is_active_titulado_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='titulado',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='titulado',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='titulado',
            name='last_login',
        ),
        migrations.AlterField(
            model_name='titulado',
            name='password',
            field=models.CharField(default='titulados', max_length=128),
        ),
    ]
