# Generated by Django 4.2.1 on 2023-10-10 16:01

import django.contrib.auth.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Web', '0015_remove_titulado_is_active_remove_titulado_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='titulado',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelManagers(
            name='titulado',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='titulado',
            name='usuario',
        ),
        migrations.AddField(
            model_name='titulado',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AddField(
            model_name='titulado',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AddField(
            model_name='titulado',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='titulado',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='titulado_set', related_query_name='titulado', to='auth.group'),
        ),
        migrations.AddField(
            model_name='titulado',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AddField(
            model_name='titulado',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.AddField(
            model_name='titulado',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='titulado',
            name='last_login',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='titulado',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='titulado',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='titulado_set', related_query_name='titulado', to='auth.permission'),
        ),
        migrations.AddField(
            model_name='titulado',
            name='username',
            field=models.CharField(default='NombreUsuario', max_length=100, unique=True),
        ),
    ]
